### ISSUE TITLE
MutateState needs annoyingly Type Arguments

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#211]
As a user of FlowRedux I need to specify explicitly the Type argiments of `MutateState`. Example:

```kotlin
sealed interface State

data class S1 (val i : Int) : State
object S2 : State
```

```kotlin
inState<S1> {
   onEnter { stateSnapshot ->
      ...
      MutateState<S1, State> { this.copy(i = this.i++) }  // MutateState needs S1 as type parameter; compiler cannot infer it.
   }
}
```

This is annoying and counterproductive to our goal of increase developer experience but I'm not sure how to solve this problem best. Some random ideas:

1. Since all blocks inside the `inState` block already know of which type the State we want to mutate is, we could add a extension function to the `onEnterBlock`, `onAction` and `collectWhileInstate` that would allow us to write something like this:
```kotlin
inState<S1> {
   onEnter { stateSnapshot ->
      ...
      mutateStateExtensionFunction { this.copy(i = this.i++) }  // this == S1 can be inferred by the compiler via extensionFuntion
   }
}
```
(Please note that `mutateStateExtensionFunction` is just a random name to illustrate the point I try to make; not the final name in case we go for this solution)
While this approach works for blocks directly defined in the DSL it would not work for functional references like this:
```kotlin
inState<S1> {
   onEnter(::doSomethingOnEnterS1)
}


fun doSomethingOnEnterS1(stateSnapshot: S1) : ChangeState<State> {
   ...
   return  stateSnapshot ->
      ...
      mutateStateExtensionFunction { this.copy(i = this.i++) }  // wont work because no such extension function defined for an aribtarry function
   }
}
```

So I was looking if it is possible to define extension functions on "Functions" but didn't figure it out yet how to do it (nor am I sure if the kotlin IDE plugin would work properly). The following did not work (but I didn't dive deeper):

```kotlin
fun <R> kotlin.Function<R>.mutateStateExtensionFunction() {...}

fun <InputState, S> ((stateSnapshot : InputState ) -> S).mutateStateExtensionFunction() {...}
```

Maybe #189  could introduce a new supertype we could define a `mutateStateExtensionFunction`  extension function on, but it doesn't look to solve the problem of function reference.

2. Another option is to go away from defining `MutateState` with receiver type.  Receiver type is handy especially with data classes used for State definition because then you can just call `copy()` to do a mutation as `this` is introduced by the compiler via `reciever type`. However, this introduces the problem that we need to tell in `MutateState` what the type of the receiver is causing developers to Explicitly specify the Generic Type Arguments.
If we would remove the receiver type, the compiler's Type inference should be smart enough to infer types (although we still need to give the compiler a hint somewhere, i.e. define the parameter type of the state snapshot):

```kotlin
inState<S1> {
   onEnter { stateSnapshot : S1 ->
      ...
      MutateState { currentState : S1 -> currentState .copy(i = currentState.i++) }  //  Explicity have defined input parameter currentState : S1  is enough for compiler to be satisfied
   }
}
```

this however doesn't fully solve the problem of developer's productivity but could be some compromise.

Do you see any other options? Do I miss something?

**Comment by gabrielittner** [comment]
Not a full solution to the problem but maybe a step to make it less of an issue. What if we split `MutateState` into 2 separate classes. We could introduce a new one that only has a single type parameter and forces you to return that type (I'd call this one mutate state) which covers the copy case. This way the type of `this` is implicitly defined based on the return type of `doSomethingOnEnterS1` which you need to define anyways. Then we could have a second new class that is essentially what `MutateState` is right now and would have the use case of transitioning to a different state subtype (could be called `TransitionState`) based on the current state when a simple `OverrideState` isn't enough.

The new simplified `MutateState` would cover the common scenario where you simply want to update the current state by copying it and `TransitionState` would cover the rest of the current `MutateState` use cases. This issue would be resolved for `MutateState` but still exist for `TransitionState`. Maybe we can go with solution 2 for `TransitionState`, it's still a compromise but the scope of it is smaller.


For solution 1 my only idea is that we could have an `interface InState<S : Any>` that is the base type for `InStateBlockBuilder`. Then the extension function could be on that and you could do `InState<S1>.doSomethingOnEnterS1`. However it's also not really shorter and testing doSomethingOnEnterS1 becomes weird because you need some fake `InState<S1>` instance to call the method.

**Comment by sockeqwe** [comment]
👍 I am, personally, not in favor though of introducing yet another option of `ChangeState` as I think it is then too confusing for users of FlowRedux (too many options and you need to know exactly which one to use and when one is preferred over the other in which case).

with that said, following up on your proposal of introducing `TransitionState` what do you think about the following:
1. remove `OverrideState(newState : S)` and replace it with `TransitionState(newState : S)`
2. Add `TransitionState( block: (currentState : S) -> S)` for the rare case when you dynamically need the current state to move to another state, so basically replacing current `MutateState<FooState, State> { OtherState( this.somePropOfFooState ) }`. in this case though `TransitionState` (unlike current `MutateState`) doesnt have 2 generics param. So in the future you would use just TransitionState for both current cases 1. OverrideState and 2. MutateState with different type of new state. code could look something like that
    ```kotlin 
     class TransitionState<S>( block: (currentState : S) -> S ) : ChangeState<S> {
           constructor(newState : S) : super( { newState }) // covers old OverrideState
     }
    ```
3. Keep `MutateState` but only with 1 generic type param as suggested by you to really just mutate on the current state. So `MutateState` still is just syntactic sugar to do casting.
   ```kotlin
     class MutateState<CurrentState : S>(CurrentState.() -> CurrentState) : ChangeState<S>
   ```
4. Keep `NoStateChange`

So the Api for change State could be `TranistionState(newState)`, `TransitionState { ... }`, MutateState<SomeState> { ... }` and `NoStateChange`


btw. to me (just personal preferences) `TransitionState` sounds quite academic and a mouthful (that was also the case with OverrideState), maybe just calling it `SetState` instead of TransitionState could be an option (i'm not sure if SetState is too ambiguous though but maybe some other name, but exact naming could be discussed  later)

## Alternative
if we stick with what we have currently (`OverrideState` and `MutateState`) but if we agree that the best we can do is to reduce generics params on `MutateState` to 1 we could think about changing implementation details, i.e. if we define `MutateState` as `fun` instead of `class`, could that help somehow? I haven't tested it yet (Im not in front of my PC) but does same function name with different generic arguments work on jvm with type erasure?

```kotlin
fun <InputState>MutateState(block : ( InputState) -> InputState) : ChangeState<InputState> { ... }
fun <InputState : S, S> MutateState( block : (InputState) -> S : ChangeState {....} 
```

then maybe using some casting and "misusing" `Nothing` type could help somehow under the hood.  what about some other Kotlin language features like new Context Receivers in 1.6.20, could they be helpful somehow?


## Radical ALTERNATIVE
another idea, a bit radical, so not sure how to feel about it but what if we remove Generics all together. motivation: there is casting that could crash at runtime already in place so if we cannot get 100% compile time safety with generics, maybe it is fine to go with almost 0 compile time safety? take `MutateState` as example:

```kotlin
inState<FooState> {
   onEnter(::doSomething)
}

suspend fun doSomething(snapshot : FooState) : ChangeState<State> {
   ...
   return MutateState<OtherState> { this.copy(...) } 
   // compiles just fine but crashes at runtime because wrong cast of FooState to incompatible OtherState
}
```

Still not sure how to feel about it but just dropping some random thought here...

**Comment by gabrielittner** [comment]
I like your first suggestion but after thinking about I think we can make it even simpler. I'm fine with calling it something other than `TransitionState`, I was mostly thinking that it highlights going to another sub state class a bit more, but I'm not hung up on it. `SetState` seems fine as well. 

One thing though about only having one type parameter, this would break this case in the [sample](https://github.com/freeletics/FlowRedux/blob/main/sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux/sample/shared/PaginationStateMachine.kt#L198-L204). In this case you can change the return type to `ContainsContentPaginationState` and it works, but there are cases were you might not have a shared super type with all the properties you need, like [here](https://github.com/freeletics/FlowRedux/blob/main/flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt#L135-L141). So having 2 parameters on `TransitionState` would still be needed, but you can at least solve it like you mentioned initially with typing out the lambda parameter.

Alternative: Kotlin can live with having both but the jvm can't, so it would work as long as you give one of them a `@JvmName`. However I think we'd still have the issue that there is no inference for `InputState` in the second one and then I prefer the other suggestion.

Radical alternative: It might not be as radical because we don't have compile time type safety for the input type of the current `MutateState` either. You could call a function that uses `MutateState<S1, State>` from somewhere in `inState<S2>` and it would crash at runtime in the reducer.


I will give the `TransitionState`/`SetState` + `MutateState`  + `NoStateChange` solution a try this week and will also test how this looks on the existing state machines in the Freeletics code base to get a feel how well the solution works.

**Comment by gabrielittner** [comment]
Another idea that's more on the radical side because it's a bigger API change: What if we would replace the snapshot parameter everywhere with something like this:
```
class State<InputState : Any>(
    val snapshot: InputState
) {
    fun <S : Any> mutate(reducer: (InputState).() -> S): ChangeState<S>
    fun <S : Any> override(s: S): ChangeState<S>
    fun <S : Any> noChange(): ChangeState<S>
}
```
This would remove the generics issue that we have right now by kind of using the snapshot type for it. It also gives type safety for the mutate state input type, which as mentioned before we didn't have before. I think it would also keep the return type type safe without you having to specify it.

```diff
  inState<FooState> {
     onEnter(::doSomething)
  }
 
- suspend fun doSomething(snapshot : FooState) : ChangeState<State> {
+ suspend fun doSomething(state : State<FooState>) : ChangeState<State> {
    ...
-   return MutateState<OtherState> { this.copy(...) }  
+   return state.mutate { this.copy(...) } 
  }
```
While nothing directly enforces that the `<S>` on the functions is a super type of `InputState` it's indirectly enforced. The `ChangeState<State>` return type will enforce that you return a `State` and then `onEnter` will enforce that the return type on your function is a `ChangeState<S>`. 

Some other things about this:
- I called the class `State` but a different name might be better since there are so many different `State` types everywhere already (like the one in compose)
- having the functions instead of the `ChangeState` subclasses might even be better for discoverability
- the impact of #288 might be a lot smaller with this, unlike the snapshot, you pretty much always need this parameter
- effect handlers could stay like they are

**Comment by gabrielittner** [comment]
I've created a prototype for this last suggestion https://github.com/freeletics/FlowRedux/compare/prototype-state

**Comment by sockeqwe** [comment]
I had something like that (a separate `State` class) in one of the very first prototypes (not exactly to solve the issue of the return type) but then I have dropped that idea because I found it not elegant and simple and would have introduced a learning curve an barrier for users of FlowRedux.

I think one of the selling point of FlowRedux is its "simplicity". The only thing you need to learn is the concept around `ChangeState` (which I dont think is ideal either but if it is only about MutateState and OverrideState then I thought it  is not too bad as a compromise to learn about a return type).

However, all solutions I had back then around `State` as an input parameter were confusing imho. I thought that maybe KSP or some other magic could help make it look good for developers somehow, but didnt find a satisfying solution.


So from my gut feeling it feels adding something not simple to reason about to solve a problem that is "just about typing less generics".


But what if we do a little "qualitative research": you could ask some Freeletics folks who have written something with FlowRedux about the new API proposal and maybe some devs who have never used FlowRedux before and ask them about their opinions. What do you think?

**Comment by gabrielittner** [comment]
Real world usability/type-safety issue that this solves that someone in our team ran into which this solves:
```
  private fun ctaClicked(
        action: CtaClicked,
        stateSnapshot: DefaultState
    ): ChangeState<UpdatingProfile> {
        return MutateState {
            UpdatingProfile(...)
        }
    }
```
compiles but crashes at runtime. As you can see from the snapshot this is used in `inState<DefaultState>`, however the type inference for MutateState will cause the current state passed to the lambda to be casted to `UpdatingProfile`.
