### ISSUE TITLE
Add more overloads for the InStateBlockBuilder methods

### ISSUE THREAD

**Issue by gabrielittner** [freeletics/FlowRedux#288]
Currently when using method references you that the Kotlin compiler will flag your parameters as unused when you just add them to be to use method references. The most common case is probably an unused `stateSnapshot`, but for the action handlers it could even be the action itself if it's just an `object`. If you don't use method references this issue still exists. While you can just use `_` to get rid of the warning you still of the verbosity of having to write out the lambda parameters (`on<SomeAction> { action, _ ->`). 

Side note that influences potential solutions: I'm getting more and more convinced that we should not use method references anymore and rely on lambdas. The general aspiration of having the `spec` block as small as possible is still valid, however I think method references are not the right solution. There are multiple issues and while some of them are not our fault and could be fixed by Kotlin they still matter:
- the initially mentioned unused parameter issue which either means you get tons of compiler warnings or need to put suppress annotations everywhere
- in some circumstances (not sure when it happens) the IDE can't really auto complete the referenced function when you're writing `::...`
- the function name should describe what it does but in practice I'm usually seeing `on(::buttonClicked)`, my assumption is that if you have `on<ButtonClicked> { ... }` you are less inclined to call the method the same
- An addition to the above is that if you do `on(::transitionToSomeState)` you loose the information of when it happens while `on<ButtonClicked> { transitionToSomeState(it) }` would make getting an overview easier. Of course you can combine both in your function name but that leads to long/weird names. For example `onButtonClickedTransitionToSomeState` is long and would then result in `on(::on...)` while leaving out the `on` from the method name reads weirdly when looking at just the function
- Method references don't work well when the method has a dependency. In practice the function is just put into the state machine class which means it's not testable on it's own anymore. While we introduced functional interfaces in #189 to make this easier, they are also a lot more verbose. If you just call a method from the lambda you can pass additional parameters to it and it keeps the syntax more aligned.

Going back to the original problem depending on whether we want to encourage method references or not all [handlers](https://github.com/freeletics/FlowRedux/blob/main/flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/Handlers.kt) would need overloads. If we are saying method references are the way to go then we'd need additional interfaces + overloads with 0 and 1 parameters for everything that has 1+ parameters. If we decide for lambdas then it would be interfaces + overloads for everything with 2+ parameters because a single parameter is just an implicit `it` either way.

**Comment by sockeqwe** [comment]
i understand and agree with all your points. still I cannot make up my mind what we should recommend. Im torn. i still would love to have the dsl spec as readable and concise as possible, but I have not written super big FlowReduxStateMachines with a lot of DSL specs yet. you have written way bigger one that I ve done, what is your experience if everything would have been written in lambdas in one big spec block? it looks most our handlers are anyway just a few lines of code (less that 10 loc I would say on average). thus maybe recommending lambdas is not too bad ...

I have just 2 thoughts about NOT using lambdas
1. my experience with kotest (also have a DSL) is that it got hard to read and maintain after a certain loc number is exceeded (dont know the exact number but I have the feeling there is a max where everything starts becoming hard to read no matter how nice the DSL per se is. i'm a bit affraid that the same could happen with FlowRedux DSL (although I see the tactics like sub state machines be an antidote which is great)
2. with fun references or handlers you could stilll write unit tests for it instead of integration / functional tests for the whole statemachine. I have also not made up my mind fully here.

so overall if you ask me, I would say, lets be unopinionated, learn over time and become more oppinionated over time as we learn (and in worst case correct things in FlowRedux 2.0). so i would be fine with adding the required overloads and keep all opptions open to the users of FlowRedux

**Comment by gabrielittner** [comment]
I'll add all overloads this week 👍 

> I have just 2 thoughts about NOT using lambdas

Both of the points assume putting all the logic into the lamdas, right? Like in kotest you write a ton of setup code into the DSL. I would use lambdas that still would call a method, so the DSL stays small and the method can be unit tested. So I was more talking about how you call the method. There could even be a lint rule a lint rule that a lambda should only contain a single statement to make sure that they stay simple.

**Comment by sockeqwe** [comment]
indeed! i was assuming logic in the lambdas but what you say makes more
sense!
