### ISSUE TITLE
DSL for additional conditions

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#310]
Just an idea that I have mixed feelings about, so dropping my idea here to hear opinions.

```kotlin
enum class MyEnum { A, B, C }
data class MyState(val e : MyEnum)


inState<MyState>(additionalCondition = { it.e == MyEnum.B }) { // means state is MyState AND state.e == B
    ... 
}
```

I am wondering if this could be expressed somehow with DSL constructs. 

For example something like adding a new `condition` DSL block like this:

```kotlin
inState<MyState> {

    condition( {it.e == MyEnum.B} ) {
        onEnter {...}
        on<Action> {...}
        collectWhileInstate { ... }

        condition (...){
              // even subcondition could be supported
         }
     }
   
    
    onEnter {...}
    on<Action> {...}
    collectWhileInstate { ... }

    ... 
}
```

That reads for me a bit nicer compared to the current `inState<S>(additionalCondition={...})`

but obviously has some disadvantages like:
- exhausting `when` functionality alike (could probably be solved with Lint checks or so)
- DSL contains more and more logic that cannot be unit tested anymore individually and reminds me a bit of too much pollated kotest DSL
- ...

Any thoughts?

**Comment by gabrielittner** [comment]
I also have something similar which is nested `inState` blocks for type hierarchies. E.g. if you have
```
sealed interface ExampleState

object ExampleA : ExampleState
sealed interface ExampleB : ExampleState
object ExampleB1 : ExampleB
object ExampleB2 : ExampleB
```
you can already have an `inState<ExampleB>` for handling that is shared between b1 and b2 and then `inState<ExampleB1>` plus `inState<ExampleB2>` for specific stuff. When reading the DSL you might not always see this hierarchy right now, which would be solved if you could put the subclass `inState` into the parent one.

Maybe these 2 can be combined so that your `condition` is also just `inState` with an inferred type parameter and the lambda is the regular `additionalCondition` parameter?
