### ISSUE TITLE
[Question] Detail page implementation help

### ISSUE THREAD

**Issue by walter-whytied** [freeletics/FlowRedux#479]
How would you advise to approach this situation. I will referencing the sample.

1. I have created `RepositoryDetailStateMachine` that needs the id of the repository to make multiple requests. I have an action `RepoClicked` that has the from the list page. What would be the best way to store the id and use it in the statemachine. Should I use `MutableStateFlow<Int>` and update it when entering the detail state?
2. Say I want to observe futre changes on loaded state. How can I implement `collectWhileInstate` and call a function returning a flow? The function depends on the id above.
```
fun flowRepositoryDetails(repoId: Int): Flow<RepositoryDetails>
```

**Comment by hoc081098** [comment]
Passing id to constructor is the best

**Comment by walter-whytied** [comment]
@hoc081098 Thanks for the quick reponse. Question about passing it to the constructor. How would that work with dagger?

**Comment by sockeqwe** [comment]
passing id as constructor is indeed best practice here. 

Speaking about best practices: you could keep the id as a `private val` such as 

```kotlin
class MyStateMachine(private val id : Int) : FlowReduxStateMachine() { ... }
```

but a more idiomatic way is to store all that data as part of the state class (instead of a private field on the state machine itself). Example:

```kotlin
data class State(val id : Int, ....)

class MyStateMachine(id : Int) : FlowReduxStateMachine( initialState = State(id = id, ...) ) { ... }
```

Regarding Dagger, Assisted Inject is what you are looking for: https://dagger.dev/dev-guide/assisted-injection.html

**Comment by gabrielittner** [comment]
+1 to everything already said. We specifically have a [navigator class](https://freeletics.github.io/mad/navigator/get-started/#naveventnavigator) that is independent from the UI so that it can be referenced from a state machine. So the list state machine gets the clicked action and would then call the navigator to go to the detail screen passing the id along. 


One other thing that I have been thinking about though? How would we handle having a tablet layout where you have list and detail next to each other? Ideally you could reuse the 2 individual list and detail state machines, however it doesn't fully work with the current sub state machine mechanism. Lets say you have a list state machine and a detail state machine, plus a third that you use on tablets to combine the state from them. That parent state machine could either handle `RepoClicked` on it's own or react to a `selectedId` or something similar changing on the main state. However how would updating the detail state machine work? The first time an item is selected you could enter a new like `ListWithDetail` in the parent state machine and then use  `onEnterStartStateMachine`, but that wouldn't work when the selected item just changes from one to another. Should there maybe be a `inState<ListWithDetail>(identity = { it.detailId })` that lets you tell FlowRedux whether 2 states are the same? With this you would leave the previous `inState` and enter it again whenever `detailId` (or whatever else you return from `identity`) changes.

**Comment by walter-whytied** [comment]
Thank you all for the pointers.  @sockeqwe I will go with the constuctor route for now. I have the ID in the state but the issue/challege was accessing the ID in `collectWhileInstate`. 

@gabrielittner The navigator class looks interesting. This is just for compose right? I will have to look for a different way of handling it on iOS. Also do you have plans to update the sample and add a detail screen or this is not a plan.

Anwyas, I appreciate the help from all of you. Really cool libary.

**Comment by gabrielittner** [comment]
> The navigator class looks interesting. This is just for compose right? I will have to look for a different way of handling it on iOS.
It's built on top of AndroidX navigation, but the general concept should be transferable and could be implemented with other navigation solutions as well. 

> Also do you have plans to update the sample and add a detail screen or this is not a plan.
Generally yes, but it's low on the priority list so I'm not sure when it will happen
