### ISSUE TITLE
FlowRedux and Flow from usecases

### ISSUE THREAD

**Issue by dzinek** [freeletics/FlowRedux#539]
Are there any examples or best practices, how to use FlowRedux with Flows get from UseCases?

I am using Room with returning lists and objects in `get*()` DAOs so the same in Repositories with UseCases. But I decided to migrate for Flows - I've already refactored data and domain layers but I stuck with StateMachine refactoring.

Should I:
* stay with `data class ShowContent(val list: List<Item>) : ListState` and collect data from flow to `items` in `load()` method in state `Loading`?
* refactor to `ShowContent(val list: Flow<List<Item>>)` and just put there flow from usecase?
* or maybe refactor to `ShowContent(val items: StateFlow<List<Item>>)` and also collect data from usecase's flow in `load()`, but then also use `collectAsState()` on StateFlow in `@Composable`?

Second case is mutating the `State` - eq. I am deleting on element from my list. Now I have:
```
    suspend fun deleteAndReplaceObjectContentOrError(
        action: Delete,
        state: State<ContentState>,
    ): ChangedState<MyObjectListState> {
        val myObject = action.myObject

        return try {
            deleteMyObject(myObject)

            state.mutate {
                val index = this.list.indexOf(myObject)
                val list = this.list.toMutableList()

                list.removeAt(index)
                this.copy(list = list)
            }
        } catch (t: Throwable) {
            state.override { Error(t) }
        }
    }
```
When I will change it to Flow, then should I collect, mutate and emit new Flow/StateFlow (depends on my first question) or a list.
Or maybe use the magic of Flows and when I run `deleteMyObject(myObject)` useCase it will persist the change in DB so the new flow will be emitted and collected with any change in list from my side?

**Comment by sockeqwe** [comment]
Hello,

> stay with data class ShowContent(val list: List<Item>) : ListState and collect data from flow to items in load() method in state Loading?

Yes, that is the idiomatic way.

Depending on what exactly you want to achieve `collectWhileInstate` might be what you looking for (see [docs](https://freeletics.github.io/FlowRedux/dsl/#collectwhileinstate)).

So I would start with "what you want to achieve" question in mind:

Wit Room + Flow, the original database query re-runs whenever the database is changed. Then you want to use `Flow` and probably use it with FlowRedux's `collectWhileInState()`

```kotlin
interface MyItemsDao{
    
    @Query("SELECT * FROM Items")
    suspend fun getAll(): List<Item> // one time query, without reruning the query on changes

   @Query("SELECT * FROM Items")
    fun getAllAsFlow():  Flow<List<Item>>. // query and observe until state changed

   @Delete
    suspend fun delete(item: Item) 
}
```

Then you have 2 options: If your app doesn't  need real time updates from the database then `dao.getAll()` and `dao.delete()` should be enough in the corresponding states and you don't need `collectWhileInState`:

```kotlin
inState<LoadingState> {
   onEnter { state -> 
     val items = dao.getAll()
     state.override { ContentState ( items) }
}

inState<ContentState> {
  on<DeleteAction> { action, state -> 
    dao.delete(action.item)
     // Instead of managing the deletion of list of items manually, 
     // you may consider simply rerruning the query
    val newItems = dao.getAll()
    state.mutate { this.copy( items = newItems ) }
  }
}
```


If you have requirements that you need to "observe" the database for changes (i.e. because another component might add, edit or delete items in the database) then you could use `collectWhileInState` but on you  want to make sure that this flow is not "cancled" accross state transition from `LoadingState` to `ContentState`. There a multiple ways to achieve that, but let's assume you have a "parent state class" all your states in that statemachine extend from, i.e. `object LoadingState : ParentState` and `data class ContentState(val items : List<Item>) : ParentState` then you could simply do something like this:

```kotlin
inState<ParentState> {
   onEnter { // This literally means when the StateMachine starts for the first time, because everything is a ParentState
       collectWhileInState(dao.getAllAsFlow()){ items : List<Item>, state : State<ParentState> ->
       when (val s = state.snapshot){
         LoadingState -> s.override { ContentState(items) }
         is ContentState -> s.mutate { this.copy(items = items) }
         else -> s.noChange()
       }
   }
}

inState<ContentState> {
 on<DeleteAction> { action, state -> 
    dao.delete(action.item)
    state.noChange() // No chage because deletion triggers Flow from Dao to emit new item and then collectWhileInState reacts again
  }
}
```

I hope that helps
