### ISSUE TITLE
[Question] Search Implementation

### ISSUE THREAD

**Issue by walter-whytied** [freeletics/FlowRedux#596]
I am checking out the sample project and I want to implement a search feature but I have having an issue with the implementation. My state never gets updated even though the API call is invoked.

My repository returns a flow of list repos. When the query changes, I invoke the repo and the list should be updated.

```
fun flowSearchResult(query: String): Flow<List<GithubRepository>>
```

The state machine looks like this:

```
     inState<SearchState> {
                on<SearchQueryChanged> { action, state ->
                   val listResult: PersistentList<SearchResult> = persistentListOf()
                    
                    searchRepository.flowSearchResult(action.query)
                        .collect {
                            listResult.addAll(it)
                        }
                    
                    
                    state.mutate { 
                        copy(
                            list = result.toPersistentList()
                        )
                    }
                }
            }
```

**Comment by sockeqwe** [comment]
The problem is that you cannot collect a flow inside an on block (or
onEnter) unless you really know what you are doing for some extreme edge
cases you normally won't have.

That is why we have collectWhileInState.

But before talking how collectWhileInState can be used, I think you can
simplify everything by just having a repository with a suspending search
function instead of a Flow. Why does your search repository have to return
Flow? Does it update search result in real time somehow or what is the
reason behind using a Flow here?

Looking at your code snipped: i think simply keep your code just change
repository to a simple suspend function (instead of flow) and the rest can
stay as it is...


walter-whytied ***@***.***> schrieb am Mo., 30. Okt. 2023,
15:33:

**Comment by walter-whytied** [comment]
Hello @sockeqwe . Tank you for getting back to me. To answer your question, the repository function fetches from the network, updates the db, and returns the cached result. That is how I have a flow implementation.

**Comment by gabrielittner** [comment]
As Hannes mentioned `collectWhileInState` is the right choice for collecting a flow. If you need to create a new flow and start collecting that whenever the search query changes you can wrap it in an `untilIdentityChanged` block where the query is the identity https://freeletics.github.io/FlowRedux/user-guide/9_untilIdentityChanged/
