### ISSUE TITLE
How does this compare to CoRedux?

### ISSUE THREAD

**Issue by inorichi** [freeletics/FlowRedux#6]
I switched from RxRedux to CoRedux and I think another switch seems unnecessary when you can integrate `Flow` into CoRedux. 

I wrote [these SideEffects](https://github.com/inorichi/tachiyomi/blob/1.x/core-ui/src/main/kotlin/presenter/SideEffects.kt) a while ago supporting Flows, and I haven't found any issue yet, that's why I'm wondering whether yet another project is really necessary.

Thoughts? Sorry if I missed something...

**Comment by sockeqwe** [comment]
Can't fully answer it yet, we will see how things are evolving, maybe they merge, maybe they don't.

some differences:
- CoRedux is really a stand alone object whereas FlowRedux is designed as an operator on a `Flow` that takes upstream Flow as input actions and which you can chain and compose easily as you would do with `Flow`(or `RxJava`).
 - CoRedux is heavily based on Channels which are scoped to a CoroutineScope. This leads to the following problem. You could have a CoRedux store that you want to share across multiple scopes, let's say in the context of android, you may want to observe the same store from multiple ViewModels with their own CoroutineScope each. CoRedux's api would allow that (you can add multiple StateReceiver / subscribers to a CoRedux Store). That leads to problems like What if one CoroutineScope get's closed while the other isn't? Also to which CoroutineScope is the CoRedux Store actually scoped? Of course to the one that originally called `.createStore()` and thus once that CoroutineScope is closed the Store wont process any input actions. However, from a public API this is not entirely clear.  FlowRedux on the otherhand is based on Flow and you have to explicitly lauch a flow inside a certain scope and can by design only have 1 subscriber (if you want to subscribe again a new store gets created with the initial state because Flow by design is a "cold stream" which means you can't share it across multiple CoroutineScopes (by design of Flow). This avoids this problem from the very beginning because Channels and Flow are fundamentally different.

With that said, there is nothing wrong by using CoRedux.

**Comment by inorichi** [comment]
Thanks for the insight.

About sharing the store, while I don't think that should be done, it should be relatively simple to write a reference counting `Job` that `cancels` when there are no subscribers left.
