### ISSUE TITLE
What makes action SelfReducableAction to be called

### ISSUE THREAD

**Issue by 3bdoelnaggar** [freeletics/FlowRedux#87]
D/TaskRequestDetailsViewModel$dispatch: FlowRedux -> action : ApproveTask(taskId=TaskReferenceId(id=45019))
D/FlowRedux: Upstream: action ApproveTask(taskId=TaskReferenceId(id=45019)) received
D/FlowRedux: Upstream: reducing Success(taskDetails=TaskDetailsUi(id=TaskReferenceId(id=45019), title=TaskTitle(value=test forward 10), progress=TaskProgress(progress=0.0), 
D/FlowRedux: SideEffect3: action SelfReducableAction Caused by on<ApproveTask(taskId=TaskReferenceId(id=45019))> received
D/FlowRedux: SideEffect3: reducing Success(taskDetails=TaskDetailsUi(id=TaskReferenceId(id=45019), title=TaskTitle(value=test forward 10), progress=TaskProgress(progress=0.0
D/TaskRequestDetailsViewModel: FlowRedux -> state : Loading(type=ACTION)
D/FlowRedux: SideEffect3: action SelfReducableAction Caused by on<ApproveTask(taskId=TaskReferenceId(id=45019))> received
D/FlowRedux: SideEffect3: reducing Loading(type=ACTION) with SelfReducableAction Caused by on<ApproveTask(taskId=TaskReferenceId(id=45019))> -> Loading(type=ACTION)

**Comment by sockeqwe** [comment]
Sorry, for my late response, I somehow overlooked this github issue.

I'm not sure if I understand your question is, can you elaborate?

If your question is what is a`SelfReduceableAction` and where is it coming from: `SelfReducableAction` is basically triggered everytíme you call  `setState { ... }` to change the state. It should not be exposed to the outside. Actually it should be renamed in the logs to `setState { ... }`  instead of exposing `SelfReducableAction`
